version: "3"

services:
  couchdb:
    image: couchdb
    environment:
      COUCHDB_PASSWORD : "couchdb"
      COUCHDB_USER : "root"
    ports:
      - 5984:5984
      - 4369:4369
      - 9100:9100
    volumes:
      - ./data:/opt/couchdb/data
      - ./labs:/app/couchdb/labs
